service: blogs-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:APP_AWS_REGION, 'ap-southeast-1'}
  httpApi:
    cors: true
  throttle:
    rate: 10 # requests per second
    burst: 20 # max concurrent requests
  environment:
    SQS_QUEUE_URL:
      Ref: TrackingQueue
    BLOG_LIKES_QUEUE_URL:
      Ref: BlogLikesQueue
    POST_DB_TABLE: Posts
    LIKE_COUNTS_DB_TABLE: LikeCounts
    TRACKING_POST_DB_TABLE: Tracking
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:TagResource"
          Resource: "arn:aws:logs:*:*:*"
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/Posts"
            - "arn:aws:dynamodb:${aws:region}:*:table/Tracking"
            - "arn:aws:dynamodb:${aws:region}:*:table/LikeCounts"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::${env:S3_MDX_BUCKET, 'please-set-in-env'}/*"
            - "arn:aws:s3:::${env:S3_MEDIA_BUCKET, 'please-set-in-env'}/*"
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - "arn:aws:sqs:${aws:region}:*:TrackingQueue"
            - "arn:aws:sqs:${aws:region}:*:BlogLikesQueue"

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
  trackingConsumer:
    handler: dist/trackings/consumer.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TrackingQueue
              - Arn
          batchSize: 10
  blogLikeConsumer:
    handler: dist/blog/consumer.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - BlogLikesQueue
              - Arn
          batchSize: 10

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-offline-sqs

custom:
  serverless-offline:
    httpPort: 3000
  serverless-offline-sqs:
    autoCreate: false
    sqs:
      - functionName: trackingConsumer
        queueName: TrackingQueue
      - functionName: blogLikeConsumer
        queueName: BlogLikesQueue

resources:
  Resources:
    TrackingQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TrackingQueue"
    BlogLikesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "BlogLikesQueue"
    PostsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Posts"
        AttributeDefinitions:
          - AttributeName: "postId"
            AttributeType: "S"
          - AttributeName: "slug"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "postId"
            KeyType: "HASH"
          - AttributeName: "slug"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    LikeCountsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "LikeCounts"
        AttributeDefinitions:
          - AttributeName: "slug"
            AttributeType: "S"
          - AttributeName: "sessionId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "slug"
            KeyType: "HASH"
          - AttributeName: "sessionId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TrackingTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Tracking"
        AttributeDefinitions:
          - AttributeName: "sessionId"
            AttributeType: "S"
          - AttributeName: "timestamp"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "sessionId"
            KeyType: "HASH"
          - AttributeName: "timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    TrackingConsumerIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "tracking-consumer-lambda-role"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "tracking-consumer-lambda-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                    - "logs:TagResource"
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: "Allow"
                  Action:
                    - "sqs:ReceiveMessage"
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                  Resource:
                    - "arn:aws:sqs:${aws:region}:*:TrackingQueue"
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                  Resource:
                    - "arn:aws:dynamodb:${aws:region}:*:table/Tracking"
