service: be-blog-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:DescribeTable"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${env:DB_TABLE}"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource:
            - "arn:aws:s3:::${env:S3_MDX_BUCKET}/*"
            - "arn:aws:s3:::${env:S3_MEDIA_BUCKET}/*"
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - "arn:aws:sqs:${aws:region}:*:TrackingQueue"

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
  trackingConsumer:
    handler: dist/trackings/consumer.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TrackingQueue
              - Arn
          batchSize: 10

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

resources:
  Resources:
    TrackingQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TrackingQueue"
    TrackingTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Tracking"
        AttributeDefinitions:
          - AttributeName: "sessionId"
            AttributeType: "S"
          - AttributeName: "timestamp"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "sessionId"
            KeyType: "HASH"
          - AttributeName: "timestamp"
            KeyType: "RANGE"
        BillingMode: "PAY_PER_REQUEST"
    TrackingConsumerIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "tracking-consumer-lambda-role"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "tracking-consumer-lambda-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: "Allow"
                  Action:
                    - "sqs:ReceiveMessage"
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                  Resource:
                    - "arn:aws:sqs:${aws:region}:*:TrackingQueue"
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                  Resource:
                    - "arn:aws:dynamodb:${aws:region}:*:table/Tracking"
